#!/bin/bash

solved=0
total=0
while read N
do
  cnt=`grep -c $N Summary.txt`
  if [ $cnt -ne 0 ] ; then
   # echo -en "X "
    ((solved++))
  else 
    echo -en "$N "
  fi
  ((total++))
done < Hard.txt

echo -en "\n"
echo "Total     = $total"
echo "Solved    = $solved"
echo "Remaining = $((total-solved))"

