#!/bin/bash

if [ "$#" -ne 1 ]; then
   echo "Please specify input file name!"
   exit;
fi

file=$1

echo "Generating report for $file ..."

solved=0
total=0
while read N
do
  cnt=`grep -c $N Summary.txt`
  if [ $cnt -ne 0 ] ; then
   # echo -en "X "
    ((solved++))
  else 
  #  echo -en "$N "
    echo `grep $N Problems.csv`
  fi
  ((total++))
done < $1

echo -en "\n"
echo "Total     = $total"
echo "Solved    = $solved"
echo "Remaining = $((total-solved))"
echo -en "\n"

